[toolchain]
channel = "nightly"
components = [
    "rustc",
    "cargo",
    "rustfmt",
    "rust-std",
    "rust-docs",
    "rust-analyzer",
    "rust-src",
    "rust-mingw",
    "llvm-tools",
    "rustc-dev"
]
targets = ["x86_64-unknown-linux-gnu"]
profile = "complete"
